export interface QuizQuestion {
    id: string; // Used for React keys internally during creation
    text: string;
    options: string[];
    correctOptionIndex: number;
    hint?: string;
}

export interface LoveQuiz {
    id: string; // UUID from Supabase
    sender_name: string;
    receiver_name: string;
    time_limit_seconds: number;
    questions: QuizQuestion[];
    created_at: string;
    score?: number;
    completed_at?: string;
}

// Omit the fields that are generated by the database
export type LoveQuizInsert = Omit<LoveQuiz, 'id' | 'created_at'>;
