/**
 * Love Rapid — Question Bank
 * 50 romantic & fun couple questions. Never fetched from the DB.
 * The API picks 5 at random on every session create / play-again call.
 */
export const QUESTIONS: string[] = [
  "What is my favorite thing about you?",
  "If we could live anywhere in the world, where would you choose and why?",
  "What is one memory of us that always makes you smile?",
  "Describe our perfect date in five words.",
  "What song reminds you of us the most?",
  "What is my biggest pet peeve?",
  "What do you think I love most about myself?",
  "If I could have any superpower, what would it be?",
  "What meal could I eat every day for a whole month?",
  "What is my go-to comfort movie?",
  "What habit of mine do you find secretly adorable?",
  "When did you first realize you had feelings for me?",
  "What is one thing you wish we did more often together?",
  "What fictional couple do we remind you of?",
  "What would I do first if I won the lottery?",
  "What is my biggest irrational fear?",
  "What emoji best represents my personality?",
  "What is the first thing I notice about a new place?",
  "How do I prefer to spend a rainy afternoon?",
  "What talent do I have that most people don't know about?",
  "What would I order at a fast-food restaurant?",
  "What is my love language?",
  "What is my most-used phrase or expression?",
  "What is my ideal holiday destination?",
  "What book or show am I most likely to recommend to everyone?",
  "What is my most prized possession?",
  "What would I change about our first date if I could go back?",
  "What is something I am proud of but never brag about?",
  "How do I act when I am stressed?",
  "What is my go-to karaoke song?",
  "What childhood memory do I talk about the most?",
  "What is one dream I have for our future together?",
  "What quirk of mine took you the longest to get used to?",
  "What is the most spontaneous thing I have ever done?",
  "What would my dream job be if money didn't matter?",
  "What is my favorite season and why?",
  "What do I do to cheer myself up when I am sad?",
  "What is the most thoughtful thing I have done for you?",
  "If I wrote a book, what would it be about?",
  "What is my guilty pleasure TV show?",
  "What do I value most in a friendship?",
  "What animal would best represent me?",
  "How do I take my coffee or tea?",
  "What is a recurring argument we have that is actually kind of funny?",
  "What is my weirdest habit?",
  "What app do I spend the most time on?",
  "What is one thing you learned about me that genuinely surprised you?",
  "How would I describe our relationship in one sentence?",
  "What is one thing you want to ask me but never have?",
  "What small thing do I do that makes the biggest difference to you?",
];

export const CHOICE_QUESTIONS: string[] = [
  "Who is more angry?",
  "Who is more romantic?",
  "Who is more stubborn?",
  "Who is more likely to fall asleep first?",
  "Who is the better cook?",
  "Who makes decisions faster?",
  "Who is more dramatic?",
  "Who is more forgetful?",
  "Who says 'I love you' more?",
  "Who is more patient?",
  "Who is more adventurous?",
  "Who is more tidy/clean?",
  "Who is more emotional?",
  "Who is more likely to spend money?",
  "Who is more talkative?",
  "Who is more protective?",
];
